module.exports = {
    context: {
        colors: [
            [
                'honey-lightest',
                'honey-lighter',
                'honey-light',
                'honey',
                'honey-dark',
                'honey-darker',
                'honey-darkest',
            ],
            [
                'gold-lightest',
                'gold-lighter',
                'gold-light',
                'gold',
                'gold-dark',
                'gold-darker',
                'gold-darkest',
            ],
            [
                'sky-lightest',
                'sky-lighter',
                'sky-light',
                'sky',
                'sky-dark',
                'sky-darker',
                'sky-darkest',
            ],
            [
                'wood-lightest',
                'wood-lighter',
                'wood-light',
                'wood',
                'wood-dark',
                'wood-darker',
                'wood-darkest',
            ],
        ],
    },
};
